name: ACT_env
channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.10
        - pip
        - pip:
                - torch
                - numpy
                - pandas
                - einops
                - tqdm
                - wandb
                - accelerate

        
